# Generated by Django 4.2 on 2023-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_services', '0002_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='servicetown',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicetown',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='town',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='town',
            name='updated_by',
            field=models.UUIDField(),
        ),
    ]
