# Generated by Django 4.2 on 2023-05-02 10:53

from django.db import migrations, models
import tersun.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('provider_services', '0004_alter_category_created_by_alter_service_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='billboard_image',
            field=models.FileField(upload_to=tersun.common.utils.get_directory),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.FileField(upload_to=tersun.common.utils.get_directory),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video',
            field=models.FileField(upload_to=tersun.common.utils.get_directory),
        ),
    ]
