# Generated by Django 4.2 on 2023-05-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_services', '0005_alter_service_billboard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicevideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
