# Generated by Django 4.2 on 2023-05-30 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tersun.common.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField()),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('other_names', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=300, null=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=300)),
                ('provider_number', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_image', models.FileField(upload_to=tersun.common.utils.get_directory)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LAPSED', 'LAPSED'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=300)),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField()),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('speculated_end_date', models.DateTimeField()),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('subscription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_id', models.UUIDField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField()),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='business_email')),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='business_phone_number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='business_whatsapp_number')),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tiktok_link', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=500, null=True)),
                ('website_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='business_profile_website')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
    ]
