# Generated by Django 4.2 on 2023-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created_by',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
