# Generated by Django 4.2 on 2023-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_created_by_alter_provider_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created_by',
            field=models.UUIDField(),
        ),
    ]
