# Generated by Django 4.2 on 2023-05-01 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('appointment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('appointment_status', models.CharField(choices=[('IN SERVICE', 'IN SERVICE'), ('FULFILLED', 'FULFILLED'), ('DUE', 'DUE'), ('CANCELED', 'CANCELED')], max_length=300)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('house_call', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=300)),
                ('pricing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('booking_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('reviewer', models.CharField(choices=[('PROVIDER', 'PROVIDER'), ('CLIENT', 'CLIENT')], max_length=300)),
                ('response_score', models.IntegerField(blank=True, default=0, null=True)),
                ('punctuality_score', models.IntegerField(blank=True, default=0, null=True)),
                ('quality_of_work_score', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider_services.service')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(through='appointments.BookingService', to='provider_services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.booking'),
        ),
    ]
