# Generated by Django 4.2 on 2023-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.UUIDField(default='85ca1206-4461-4924-a78a-8854b5c5e450', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_by',
            field=models.UUIDField(default='85ca1206-4461-4924-a78a-8854b5c5e450'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='updated_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_by',
            field=models.UUIDField(),
        ),
    ]
