# Generated by Django 4.2 on 2023-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='created_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.UUIDField(),
        ),
    ]
